libsdl-org/SDL_image

- CMakeLists.txt
Hello.
This patch fixes two problems that I've encountered with SDL_image.
1) It didn't allow me to build it as a static library - `add_library` was called with `SHARED` flag, so `BUILD_SHARED_LIBS` had no effect.
2) I build SDL_image with SDL2 in a "superbuild" way by doing this:
```cmake
add_subdirectory(sdl2_src)
add_subdirectory(sdl_image_src)
```
Unfortunately, `find_package` didn't allow me to do it, because SDL2 was not found system-wide (it's not built when I call add_subdirectory). However, if you don't call `find_package` if `SDL2` target is present, this will work, because SDL2 will be compiled later and will successfully link with SDL_image afterwards.
> CMake improvements: see if SDL2 target is defined; allow to build as a static library

- .gitignore
- CMakeLists.txt
- external/jpeg-9d/CMakeLists.txt
Hello. This patch is a lot more complex than my previous CMake one, but it's not possible to fix only one thing at a time, unfortunately.
Currently, the CMake build is broken in several places and here's what this patch does:
* Link to a correct SDL target depending on build type (static or shared)
* Link to a correct libpng target based on the build type
* Fix libjpeg build (`jmemansi.c` wasn't included in the build)
* Fix showimage build on Windows - need to link to SDL2main
* Use bundled zlib for build
* Fix webp build (it doesn't add needed include directory for some reason)
* Add zconf.h to gitignore - maybe it should be deleted from the repo even? It's generated during the build of zlib in the binary dir. And zlib's CMake renames `zconf.h` to `zconf.h.included` in the source …
> More CMake fixes

- CMakeLists.txt
- Basically, I've copied settings from configure file and Makefile.am
- Now apple Image I/O is used by default.
Fixes #168 
#169 also contained some of the changes but they were not complete.
> Fix CMake problems when building under macos

- showimage.c
This allows showimage to be used as a non-interactive smoke-test to
check that the SDL2_image library can be linked against successfully,
for example as used in the Steam Runtime:
xvfb-run ./showimage -quit -save debian-logo.bmp /usr/share/pixmaps/debian-logo.png
---
We've been applying this in the Steam Runtime for a while, and using it in an [autopkgtest script](https://salsa.debian.org/ci-team/autopkgtest/blob/master/doc/README.package-tests.rst) (the command-line quoted is a simplified version of the real script). I'd like to do the same in Debian proper, but I'd feel more comfortable about that if this change was applied upstream.
> showimage: Add a -quit option

- CMakeLists.txt
- external/zlib-1.2.11/CMakeLists.txt
CMake build when including SDL_image as git submodule was broken for unix:
```
$ make
[  1%] Generating pnglibconf.c
[  2%] Generating pnglibconf.out
/home/cvarner/workspace/game-template/build/external/SDL_image/external/libpng-1.6.37/pnglibconf.c:34:11: fatal error: zlib.h: No such file or directory
34 | # include <zlib.h>
|           ^~~~~~~~
compilation terminated.
CMake Error at scripts/genout.cmake:78 (message):
Failed to generate
/home/cvarner/workspace/game-template/build/external/SDL_image/external/libpng-1.6.37/pnglibconf.out.tf1
```
looking at the `scripts/genout.cmake` created by cmake, you can see how the includes are generated
```
set(INCDIR "/home/cvarner/workspace/game-template/build/external/SDL_image/external/libpng-1.6.37")
...
set(ZLIBINCDIR "external/zlib-1.2.11") …
```
> Fix cmake build for git submodules on unix

- IMG_bmp.c
This adds support for decoding images with 24 bits colors
that are similar to 32 bits without the alpha channel, the
mask is used for visibility instead.
Tested with ICO images contained in a ANI formatted cursor animation and they properly display.
> IMG_bmp.c: Add support for 24 bits ICO/CUR images

- IMG_gif.c
This isn't mentioned in the header file and it returns a type that
callers cannot understand without knowing internal implementation
details, so I assume it was meant to be private to SDL_image.
> gif: Don't import internal function IMG_LoadGIF_RW_Internal

- showanim.c
Similar to showimage -quit, this allows it to be used as a
non-interactive smoke-test.
> showanim: Add a command-line option to loop once and then exit

- IMG.c
The documentation here: https://www.libsdl.org/projects/SDL_image/docs/SDL_image_8.html seems to indicate that the return value of IMG_Init() should be:
```
Returns: a bitmask of all the currently initted image loaders. 
```
This change updates the behavior to match this. With this change, if IMG_Init is called with a single flag set, but other loaders had already been initialized, they will be indicated as initialized in the return value.
> Update IMG_Init() return value to match documentation

- configure
- configure.ac
Checking the results of `gcc -print-search-dirs` doesn't work correctly since it uses different path separators on MSYS compared to what autoconf detects (';' instead of ':').
> Fix detection of dynamic libraries with MinGW (SDL2)

- configure
- configure.ac
Checking the results of `gcc -print-search-dirs` doesn't work correctly since it uses different path separators on MSYS compared to what autoconf detects (';' instead of ':').
> Fix detection of dynamic libraries with MinGW (SDL 1.2)

- IMG_png.c
Add support for saving `tRNS chunk` (transparency for palette)
No convertion `RGB24` -> `RGBA32`, if we can just save `RGB24` (good for saving speed and file size)
Also I recommend you make small (or not) refactoring of file `IMG_png.c` in the future
For example, last 5 lines of `IMG_SavePNG_RW_libpng` or all code of `IMG_SavePNG_RW` writed in bad style
> fix #206 (png-saving for RGB24 and palette with transparent)

- CMakeLists.txt
The `set()` call needs to be placed before `add_subdirectory()` to ensure the subdirectory sees the proper option.
I also saved the boolean in the cache to prevent overrides, but I'm not sure if that's interesting; I'm open to remove it if necessary.
> Fixed disabling the zlib installer

- configure.ac
The use of square brackets for a character set collides with the use
of square brackets for m4 quote characters, so use the other quoting
mechanism that Autoconf provides, by escaping [ as @<:@ and so on.
---
Same as libsdl-org/SDL#5620.
@slouken, @sezero: After merging, please regenerate the Autotools goo.
> configure.ac: Use Autoconf quadrigraphs for character set in AS_CASE

- .github/workflows/main.yml
- CMakeLists.txt
Fix remaining issues (apart from the dependency issues) not solved by https://github.com/libsdl-org/SDL_image/pull/189:
- fix dynamic loading of dependencies on Windows: find dll using dlltool/dumpbin
- dynamic loading on linux finds same libraries as autotools
result of github actions (using system packages): https://github.com/madebr/SDL_image/actions/runs/2308670000
> Use dlltool/dumpbin to find corresponding dll's for import libraries

- CMakeLists.txt
- SDL2_imageConfig.cmake.in
- Export a `SDL2_image::SDL2_image` target instead of a `SDL2::image` target
- Allow parallel installs of shared and static SLD2_Image:
a `SDL2_image::SDL2_image` target for a shared build, and a `SDL2_image::SDL2_image-static` target for a static build
This allows the following:
```cmake
cmake_minimum_required(VERSION 3.10)
project(exampleproj)
find_package(SDL2 REQUIRED)
find_package(SDL2_image REQUIRED)
add_executable(showimage showimage.c)
target_link_libraries(showimage PRIVATE SDL2_image::SDL2_image SDL2::SDL2)
add_executable(showimage_static showimage.c)
target_link_libraries(showimage_static PRIVATE SDL2_image::SDL2_image-static SDL2::SDL2-static)
```
This is mostly useful for distributions who distribute both shared and static libraries.
A cmake install prefix might look like the …
> Change CMake export name + allow parallel installs of static/shared SDL2

- IMG_jpg.c
Linux distributions like to control the number of image loading/saving
implementations they are compiling, because each one comes with a risk
of security vulnerabilities.
If we've built with --disable-stb-image and --disable-jpg-shared
(ordinary linking with -ljpeg, as opposed to using dlopen()) then
initializing libjpeg can't fail: either it's present and works, or
loading SDL_image would have failed in the runtime linker. As a result,
there's no point in having the code path that can fall back to tiny_jpeg
in this configuration.
> Don't link tinyjpeg if we have a hard dependency on libjpeg

- showimage.c
I added the -quit option for simple automated testing (with hindsight,
perhaps "-quit-after-loading" would have been a better name). The
intention was that something like
showimage -quit -save out.bmp in.jpg -save out2.bmp in.png
would go through the motions of loading each image, save it to the
corresponding output file, but not actually wait for input or rendering.
---
I've started trying to learn the SDL_test framework well enough to add an automated test with better coverage, but that PR isn't ready yet, and probably shouldn't be considered a blocker for 2.5.1.
> showimage: Restore automation-friendly behaviour of -quit

- test/CMakeLists.txt
Suggested by @madebr on #245.
A 30 second timeout happens to be the default in Meson, but otherwise
this is completely arbitrary.
Under normal circumstances, our only test so far takes about 1 second,
so this gives us plenty of headroom for slower architectures or
additional test coverage in future.
> test: Set a timeout for unit tests

- test/Makefile.am
- test/Makefile.in
We'll need this if we want to build with --enable-installed-tests
from an official source release, which I'd like to do in Debian.
> test: Distribute template.test.in in source release tarballs

- .github/workflows/main.yml
- test/Makefile.am
* Fix name of Linux static build job
* Revert "workflows: Run the automated test for CMake builds"
This reverts commit 72d9524536a34273210fab434d1c14f212ffd937.
Building in this mode is failing; let's get the CI green again before
fixing this.
* workflows: Disable automated test on macOS for now
Various test failures are under investigation (see #248).
> Revert CI regressions

- CMakeLists.txt
The CMake script was always looking for zlib, even when it was not needed.
Also fix a cmake error when configuring with an early cmake version (3.16.3).
> cmake: zlib is only needed by libpng + fix configuring with cmake 3.16

- IMG_jpg.c
- IMG_qoi.c
- IMG_svg.c
- tiny_jpeg.h
* jpg: Fix channel order of saved JPEGs on big-endian platforms
Both of the JPEG libraries we use (jpeglib or tinyjpeg) expect to see
the red channel in the first byte of the buffer, regardless of whether
the first byte is considered to be the most-significant or
least-significant in native endianness.
* tiny_jpeg: Don't byteswap 16-bit words if already big-endian
Previously, this assumed that native endianness was always little-endian,
which is true for x86 and most other architectures, but untrue for
some (mostly older) unusual architectures.
Forwarded: https://github.com/serge-rgb/TinyJPEG/pull/16
* qoi: Fix channel order on big-endian platforms
qoi.h always decodes the red channel of the first pixel into the first
byte of the buffer, regardless of whether interpreting the buffer as
a …
> Fix some formats on big-endian machines

- test/CMakeLists.txt
- test/Makefile.am
Fixes: b1f650d "Added PCX and TGA sample files for testing"
> test: Add PCX and TGA samples to list of test data

- .github/workflows/main.yml
- CMakeLists.txt
- cmake/FindPrivateSDL2.cmake
The reasoning behind this extra github workflow dependency is enforcing compatibility with the minimum required cmake version we declared at the top of the cmake build script.
> Use specific CMake version on github workflow

- IMG_svg.c
- nanosvg.h
- nanosvgrast.h
This imports the following four commits from mainstream nanosvg:
https://github.com/memononen/nanosvg/commit/3cdd4a9d788695699799b37d492e45e2c3625790
https://github.com/memononen/nanosvg/commit/ccdb1995134d340a93fb20e3a3d323ccb3838dd0
https://github.com/memononen/nanosvg/commit/214cf85efcdc67524335ad0e2a2d5982246b6a72
https://github.com/memononen/nanosvg/commit/3bcdf2f3cdc1bf9197c2dce81368bfc6f99205a7
This adds roundf() as a new dependency: Since SDL_roundf() requires
SDL >= 2.0.16, invented a tiny local `SDLIMAGE_roundf()` function for
it instead.
> nanosvg: sync with mainstream:

- IMG_stb.c
- stb_image.h
This upgrades stb_image.h to newest mainstream version and applies
some fuzz fixes from mainstream pull requests: There are a lot of fixes
applied to the library and ours was left quite behind.
CC: @flibitijibibo as the original author submitted the stb_image support.
> stb_image.h: upgrade to newest mainstream version

- sdl2_image-config.cmake.in
If we gain a dependency on a library with "-" in its name, we'd parse
the list of dependencies incorrectly; fix that. Equivalent to
https://github.com/libsdl-org/SDL/pull/5789 in SDL.
> cmake: Fix static linking to dependencies with "-" in library name

- IMG_png.c
For #282.
Sometime between SDL 2.0.5 and today, RGB24 PNG saving support was added. (See the relevant code section in 2.0.5: https://github.com/libsdl-org/SDL_image/blob/release-2.0.5/IMG_png.c#L570-L591, versus now: https://github.com/libsdl-org/SDL_image/blob/prerelease-2.5.2/IMG_png.c#L631-L633)
But it only checks if the surface is exactly RGB24. If the surface is BGR24, or any other format that doesn't have an alpha channel, it is converted to RGBA32 anyways.
This patch makes the behavior more consistent, because BGR24 or RGB24 are both saved as RGB PNGs (as opposed to RGBA PNGs or Paletted PNGs).
> More consistent RGB PNG saving with LIBPNG

- IMG_gif.c
- IMG_lbm.c
- cmake/test/CMakeLists.txt
From another project I learned about a tool called codespell that helps you find typos in source code. https://pypi.org/project/codespell/.
I found a few and fixed a few. I'm surprised there weren't more actionable ones.
> Minor typo fixes

- Xcode/SDL_image.xcodeproj/project.pbxproj
Currently it's impossible to build static library target from command line with `xcodebuild` because of error:
> ApplicationServices is not available when building for iOS. (in target 'Static Library' from project 'SDL_image')
This PR fixes that by marking ApplicationServices framework as macOS-only (same as in the framework target).
However, it's interesting that with Xcode GUI it's possible to build for device (when you select "any iOS device" as destination) without any modifications. I tried to pass the `-destination` option to `xcodebuild`, but that didn't help. Maybe Xcode uses some undocumented variable to control this behaviour. Here's my build script: https://github.com/kambala-decapitator/vcmi-ios-depends/blob/e8528fe3ca3e3865d85718adc02acbf47209ecb3/build_depends.sh#L154
> fix linking options of Xcode's static library target

- IMG_png.c
This is a quickfix PR for two warnings reported by clang.
The first issue is `sizeof(png_colorp)` should really be `sizeof(png_color)` (because `png_colorp` is a pointer type)... Fortunately `sizeof(png_colorp)` is 4 or 8 depending on the platform and `sizeof(png_color)` is a 3 so this code was only mallocing more space than needed and not less. But now I fixed it to malloc the exact size.
Second issue was that `color_ptr` was being leaked in an early-exit-on-error case
> Fix wrong size malloc and minor memleak

- CMakeLists.txt
target_link_options cannot be used because it does not support static libraries
> cmake: use target_link_libraries to add link options

- CMakeLists.txt
- build-scripts/android-prefab.sh
This is the SDL_image equivalent for https://github.com/libsdl-org/SDL/pull/6291.
This script creates a SDL2_image Android aarchive that can be dropped into an Android project.
If the aar is uploaded to a central repository, then the user does not need to build SDL_image himself.
Example of an archive created by this script: [SDL2_image-2.7.0.zip](https://github.com/libsdl-org/SDL_image/files/9691318/SDL2_image-2.7.0.zip)
The script needs to be executed similarly to the one of SDL with a small  difference: it needs to know the location of sdl2.
This information is passed by an environment variable `sdl_build_root`. That path should be the build folder of the android prefab script of SDL2.
I tested this with the following command:
```
docker run --rm -ti -v $PWD:/src:z -v …
```
> Android: add script for building prefab archive

- .github/workflows/main.yml
Homebrew provides SDL2 2.24.1, so use the prebuilt binary
Closes #299
> Don't use sdl2 --HEAD on Apple CI

- IMG_bmp.c
`biBitCount` is used on line 761 to infer the default palette size if `biClrUsed` is zero, but is set to 8 here for no apparent reason. Of course a 16-color image doesn't have a 256-color palette. It seems the bug has existed forever.
Example 4-bit .ico file that fails to load before but loads with this patch:
PR'd to `release-2.6.x` branch out of optimism that this fix could make it into a future 2.x release; I don't know your backport policy. Can rebase if needed.
> Fix loading of 4-bit .ico files

- IMG_tif.c
- IMG_webp.c
Just fix unused parameter for non-supported loaders yet.
```
/home/markand/dev/github/SDL_image/IMG_tif.c: In function ‘IMG_isTIF’:
/home/markand/dev/github/SDL_image/IMG_tif.c:236:26: warning: unused parameter ‘src’ [-Wunused-parameter]
236 | int IMG_isTIF(SDL_RWops *src)
|               ~~~~~~~~~~~^~~
/home/markand/dev/github/SDL_image/IMG_tif.c: In function ‘IMG_LoadTIF_RW’:
/home/markand/dev/github/SDL_image/IMG_tif.c:242:40: warning: unused parameter ‘src’ [-Wunused-parameter]
242 | SDL_Surface *IMG_LoadTIF_RW(SDL_RWops *src)
|                             ~~~~~~~~~~~^~~
[ 65%] Building C object CMakeFiles/SDL3_image.dir/IMG_webp.c.o
/home/markand/dev/github/SDL_image/IMG_webp.c: In function ‘IMG_isWEBP’:
/home/markand/dev/github/SDL_image/IMG_webp.c:387:27: warning: unused parameter …
```
> Fix unused parameter warning

- tiny_jpeg.h
Define TJEI_FORCE_INLINE as static __forceinline
This fixes the following warning(s) when built with clang on Windows:
```
warning: static function 'tjei_write' is used in an inline function with external linkage [-Wstatic-in-inline]
note: use 'static' to give inline function 'tjei_write_bits' internal linkage
note: expanded from macro 'TJEI_FORCE_INLINE'
```
> Fix warnings caused by -Wstatic-in-inline [SDL2]

- tiny_jpeg.h
Define TJEI_FORCE_INLINE as static __forceinline
This fixes the following warning(s) when built with clang on Windows:
```
warning: static function 'tjei_write' is used in an inline function with external linkage [-Wstatic-in-inline]
note: use 'static' to give inline function 'tjei_write_bits' internal linkage
note: expanded from macro 'TJEI_FORCE_INLINE'
```
Fixes #349
> Fix warnings caused by -Wstatic-in-inline

- .github/workflows/main.yml
This is a first step in fixing https://github.com/libsdl-org/SDL/issues/6667 and https://github.com/libsdl-org/SDL/issues/7219.
I've created a GitHub action at https://github.com/madebr/setup-sdl, that can be included in a workflow yaml using:
```yml
- name: Set up SDL
id: sdl
uses: madebr/setup-sdl@master
with:
version: 3-head
```
The arguments are listed in [`action.yml`](https://github.com/madebr/setup-sdl/blob/master/action.yml#L3-L11).
- 2.x.y: use a particular SDL2 release
- 2-any: use any SDL2 release
- 2-latest: use the latest SDL2 release
- 2-head: use the SDL2 branch from the SDL repo
- 3-head: use the main branch from the SDL repo
- git hash: use a particular git hash from the SDL repo
It simply builds SDL with everything defaulted, and no caching.
Also, no system dependencies …
> ci: try my experimental setup-sdl action

- test/CMakeLists.txt
Otherwise we won't have the definitions like -DLOAD_BMP that tell us whether each format is meant to be supported, which this test needs to know.
> test: Copy compile definitions from the shared library

- CMakeLists.txt
- cmake/SDL3_imageConfig.cmake.in
- cmake/sdl3-image.pc.in
- cmake/test/CMakeLists.txt
- test/CMakeLists.txt
- It's not possible anymore to build the SDL_image tests as a standalone project
- make `sdl3-image.pc` relocatable (you can move the install prefix of SDL_image without worrying about absolute paths)
> cmake: remove ability to build standalone tests + relocatable sdl3-image.pc

- test/template.test.in
The build system switched from naming the executable ${exe} to naming it ${TARGET}.
Fixes: 9ed663af "cmake: use add_sdl_image_test_executable function"
> Update test/template.test.in for build system changes

- CMakeLists.txt
This PR allows for building with cmake's [add_subdirectory](https://cmake.org/cmake/help/latest/command/add_subdirectory.html#command:add_subdirectory) function, like so:
```shell
add_subdirectory(lib/SDL2_image lib/SDL2_image_BIN EXCLUDE_FROM_ALL)
target_link_libraries(main PRIVATE SDL2_image)
```
> Use CMAKE_CURRENT_*_DIR instead of CMAKE_*_DIR

- configure
- configure.ac
Before this, configure used to find dylibs like this:
```
-- dynamic libwebp -> libwebp.dylib
-- dynamic libwebpdemux -> libwebpdemux.dylib
-- dynamic libavif -> libavif.dylib
-- dynamic libjxl -> libjxl.dylib
```
However, libXXX.dylib are most usually symlinks to their versioned ones
i.e. libXXX.N.dylib, therefore it was the wrong thing to do.
After this, it finds the dylibs like this: (configure script was
deliberately run with `--disable-stb-image --disable-imageio` in order
to find all possible dylibs) :
```
-- dynamic libwebp -> libwebp.7.dylib
-- dynamic libwebpdemux -> libwebpdemux.2.dylib
-- dynamic libavif -> libavif.16.dylib
-- dynamic libtiff -> libtiff.5.dylib
-- dynamic libjpeg -> libjpeg.9.dylib
-- dynamic libpng -> libpng16.dylib
-- dynamic libjxl -> libjxl.0.8.dylib
```
As …
> [SDL2] fixes to autotools find_lib usage for mac (and windows)

- src/IMG_lbm.c
The PR https://github.com/libsdl-org/SDL_image/pull/318 introduced a regression, loading some kinds of `LBM` files now segfaults. 
[Here](https://github.com/libsdl-org/SDL_image/files/13696574/magenta.zip) is a zip that contains one such LBM file that segfaults on 2.8.x but not on earlier versions.
This PR does a simple fix
> Fix regression (segfault) in LBM image loading [SDL2 branch]

- src/IMG_png.c
Reference issue: https://github.com/libsdl-org/SDL_image/issues/416
> IMG_png.c: remove volatile keywords handle longjmp issues better

- src/IMG_jpg.c
* JPEG: Factor out the middle of IMG_SaveJPG_RW_jpeglib
No functional change intended. We'll need to use setjmp() in this
function in a subsequent commit, so ensure that its state doesn't
include any local variables that are used both "above" and "below"
the stack level at which we will call setjmp().
* JPEG: Add error-recovery when saving with libjpeg
Because we have set up libjpeg to use my_error_exit, we need to call
setjmp() before the first time it might possibly call longjmp().
Otherwise, on error we'll do a non-local goto to an uninitialized
pointer and crash.
---
SDL3 version of #432. Untested (there's no SDL3 in the scout SDK yet) but the only difference is the name of a constant.
> JPEG: Handle errors when saving with libjpeg

- src/IMG_jpg.c
* JPEG: Factor out the middle of IMG_SaveJPG_RW_jpeglib
No functional change intended. We'll need to use setjmp() in this
function in a subsequent commit, so ensure that its state doesn't
include any local variables that are used both "above" and "below"
the stack level at which we will call setjmp().
* JPEG: Add error-recovery when saving with libjpeg
Because we have set up libjpeg to use my_error_exit, we need to call
setjmp() before the first time it might possibly call longjmp().
Otherwise, on error we'll do a non-local goto to an uninitialized
pointer and crash.
---
SDL2 version of #431, which should be merged first (but this is the version that I have actually tested). Please cherry-pick to release-2.8.x if accepted.
> [2.x] JPEG: Handle errors when saving with libjpeg

- CMakeLists.txt
When using CMake >= 3.28, the build on Windows can fail with the following error:
~~~
-- Found TIFF: D:/bld/sdl2_image_1711371034934/_h_env/Library/lib/cmake/tiff (found version "4.6.0")
CMake Error at cmake/PrivateSdlFunctions.cmake:247 (message):
TIFF::TIFF is not a shared library, but has type=INTERFACE_LIBRARY
-- Dynamic libtiff: $<TARGET_FILE_NAME:TIFF::TIFF>
Call Stack (most recent call first):
-- SDL2_image: Using system libwebp
~~~
The error is due to https://gitlab.kitware.com/cmake/cmake/-/merge_requests/8803, that changed `TIFF::TIFF` to be an interface library that just acts as a sort of alias to `TIFF::tiff`. This PR fixes this problem by using `TIFF::tiff` if it is defined, and just use `TIFF::TIFF` if `TIFF::tiff` is not defined.
> Fix SDL2IMAGE_TIF_SHARED=ON and SDL2IMAGE_TIF_VENDORED=OFF when using CMake >= 3.28

- src/IMG_png.c
- src/IMG_tga.c
Changed `SDL_PIXELFORMAT_RGB555` to `SDL_PIXELFORMAT_XRGB1555`.
Been building for android and this makes the build fail, so I fixed it.
> Migrate an SDL2 symbol to the SDL3 one

- src/IMG.c
fixes that the emscripten build is no longer succeeds due to libsdl-org/SDL#10243
> Update to the latest version of SDL

- src/IMG_avif.c
- src/IMG_jxl.c
@slouken @sezero Remaining two instances.
P. S. Missed in the earlier PR because I did not need them to build 2.8.2: apparently, MacPorts skips these files by default.
See also: https://github.com/libsdl-org/SDL_image/pull/463#issuecomment-2287162843
> IMG_*: fix remaining cases of incorrect attribute placement

- cmake/Findwebp.cmake
I faced an error when building on Linux (via Conan Center Index CI) because of the case mismatch. However, on my local machine running macOS there was no issue. This was for v2.8.2, but I see that v3 has the same issue.
```
sdl_image/2.8.2: RUN: cmake -G "Unix Makefiles" -DCMAKE_TOOLCHAIN_FILE="generators/conan_toolchain.cmake" -DCMAKE_INSTALL_PREFIX="/home/conan/workspace/cci_prod_PR-25991/conan-home/p/b/sdl_ida4af7139f2bc/p" -DCMAKE_POLICY_DEFAULT_CMP0091="NEW" -DCMAKE_BUILD_TYPE="Release" "/home/conan/workspace/cci_prod_PR-25991/conan-home/p/b/sdl_ida4af7139f2bc/b/src"
-- Using Conan toolchain: /home/conan/workspace/cci_prod_PR-25991/conan-home/p/b/sdl_ida4af7139f2bc/b/build/Release/generators/conan_toolchain.cmake
-- Conan toolchain: Defining architecture flag: -m64
-- Conan …
```
> fix name case of webpdemux target

- CMakeLists.txt
- cmake/cmake_uninstall.cmake.in
The code is yoinked from the SDL repo. Works fine on my machine.
```
chiller@debian:~/Desktop/git/SDL_image/build$ sudo make install
[sudo] password for chiller: 
[ 84%] Built target SDL3_image-shared
[ 92%] Built target showanim
[100%] Built target showimage
Install the project...
-- Install configuration: ""
-- Installing: /usr/local/lib/libSDL3_image.so.0.1.0
-- Up-to-date: /usr/local/lib/libSDL3_image.so.0
-- Set runtime path of "/usr/local/lib/libSDL3_image.so.0.1.0" to ""
-- Up-to-date: /usr/local/lib/libSDL3_image.so
-- Installing: /usr/local/include/SDL3_image/SDL_image.h
-- Installing: /usr/local/lib/cmake/SDL3_image/SDL3_imageConfig.cmake
-- Installing: /usr/local/lib/cmake/SDL3_image/SDL3_imageConfigVersion.cmake
-- Installing: …
```
> cmake: add uninstall target

- external/Get-GitModules.ps1
- external/download.sh
Not a big change but because my internet speed is always low in my area, I always encounter the problem when external libraries can't be cloned completely (especially libjxl, git failes with RPC call and I assume it's because of country middleboxes...). Everytime, I had to add this flag manually, but I think it won't harm much if it is included in the main repo + it will speed up the download process anyway.
> Added `--depth 1` flag for cloning external libraries

- external/Get-GitModules.ps1
Windows handles arguments passed to processes differently. In PowerShell script, need to explicitly pass array of arguments to `git clone` command. This PR addresses that issue.
> Fixed default arguments not being passed properly in external dependencies powershell script

- configure
- configure.ac
- ltmain.sh
Cherry-picked from SDL2 commit 4a28594.
> autotools: Eliminate libgcc*.dll dependency in mingw builds. (SDL 1.2)

- CMakeLists.txt
- do not set PNG_BUILD_ZLIB: it's rejected by libpng with error.
set ZLIB_ROOT, instead.
- set SKIP_INSTALL_CONFIG_FILE for the SDLIMAGE_ZLIB_SHARED case
because libpng cmake config fails for zlibstatic.
> cmake: adapt to the new vendored libpng cmake'ry :

- src/miniz.h
I recently tried out the new SDL3 libraries and noticed that creating PNG images with **IMG_SavePNG** created much bigger files than before (~5MB instead of ~1.7MB).
The library was built with **SDLIMAGE_BACKEND_STB=ON** and I saw that miniz will be used in this case, so I looked into changes of **miniz.h** between SDL2 and SDL3. I've noticed that some macros were wrapped into do-while-zero loops, but those macros contain break-commands for the outer loop.
This change removes the loop wrappers, but also additional semicolons which were the reason for the previous change. This seems to have fixed the issue and files are small again.
> Fixed saving PNG images with miniz creating files with 3 times the expected size

- CMakeLists.txt
(cherry picked from commit 5df4a32e14a3ed46ef0a4f33132c831331ef0b8f)
sdl2 backport of #539
> Disable sjpeg and openexr support of vendored libjxl

- CMakeLists.txt
> cmake: disable SDLIMAGE_(AVIF|JPG|PNG)_SAVE when backends are not available

- src/IMG_jpg.c
- src/IMG_png.c
Closes: https://github.com/libsdl-org/SDL_image/issues/435
CC: @smcv
> factor out parts of IMG_LoadJPG where locals can be clobbered by longjmp (SDL2 version)

- src/IMG_jpg.c
- src/IMG_png.c
Closes: https://github.com/libsdl-org/SDL_image/issues/435
CC: @smcv
> factor out parts of IMG_LoadJPG where locals can be clobbered by longjmp (SDL3 version)

- src/IMG_stb.c
Hello, the `SDL_PREALLOC` flag should be cleared before `SDL_ConvertSurfaceFormat`, so that the pixels would be freed.
> IMG_stb: Fix a memory leak for PNG.

- CMakeLists.txt
The `ApplicationServices` framework, which includes `ImageIO`-specific definitions, is not available on `iOS`. It was removed in [Issue 470](https://github.com/libsdl-org/SDL_image/issues/470), and no replacement is currently linked for `iOS` builds.
As a result, without linking the appropriate `iOS` frameworks, the [`ImageIO`](https://developer.apple.com/documentation/imageio)  backend won't function on `iOS`.
However, [`ImageIO`](https://developer.apple.com/documentation/imageio) itself has been available on `iOS` since version `4.0`.
A temporary workaround is to disable the `ImageIO` backend for `iOS` builds, although there don’t appear to be any technical reasons preventing its use:
```cmake
set(SDL2IMAGE_BACKEND_IMAGEIO OFF)
```
To enable `ImageIO` support on `iOS`, the build should …
> ISSUE-470: add CoreGraphics, ImageIO, and MobileCoreServices required from `IMG_ImageIO.mm` for `iOS`-specific builds

- docs/INTRO-visualstudio.md
The original guide was missing the steps for adding the SDL3 include directories and the SDL3 reference in the SDL3_image project. I have added these steps.
> improve INTRO-visualstudio.md with more detailed Visual Studio steps

- src/IMG_ImageIO.m
Hi
This PR makes IMG.c keep trying to load an image if another format fails.
The reason I even had this problem comes from trying to load [this](https://limewire.com/d/MjcEJ#YABhdMq1F8) WebP image on iOS (I could not attach it to PR as GitHub does not support this format)
For some reason, this image was recognized as a TIF format image by the `UTTypeConformsTo`. I tried replacing it with the `UTTypeEqual`, but got the same result. The image load was failing because the TIF format check was performed before checking against WEBP.
While the problem I had is likely some rare edge case, I believe it would still be a good thing to try to handle such rare hiccups.
> IMG.c: Loader now keeps trying other formats, if other supported format(s) failed to load an image

- src/IMG_avif.c
- src/IMG_bmp.c
- src/IMG_gif.c
- src/IMG_jpg.c
- src/IMG_jxl.c
- src/IMG_lbm.c
- src/IMG_pcx.c
- src/IMG_png.c
- src/IMG_pnm.c
- src/IMG_qoi.c
- src/IMG_svg.c
- src/IMG_tga.c
- src/IMG_tif.c
- src/IMG_webp.c
- src/IMG_xcf.c
- src/IMG_xpm.c
- src/IMG_xv.c
- src/IMG_xxx.c
Currently, when various backends are disabled, GCC and clang spit out a large number of warnings due to unused parameters. The code already uses a pragma to disable these warnings on MSVC (mostly), but not other compilers, as well occasionally using void statements to silence individual cases.
This PR just standardises things by always using void statements to silence the warnings, which works with all compilers and removes the need for any pragmas.
> fix unused paramater warnings

- src/IMG_webp.c
IMG_LoadWEBP_IO and IMG_LoadWEBPAnimation_IO_Internal get the position at the beginning and set it back to the stream if the operation fails. Following this standard, the same was added to our new save function, so it behaves the same.
> Seek stream to the beginning if error in IMG_SaveWEBP_IO

- src/IMG_gif.c
Destroys the created image surface if NormalizeFrames fails so we don't silently leak memory.
This fixes #583
> Destroy image if NormalizeFrames fails in GIF Animation

- src/IMG_xcf.c
In file `src/IMG_xcf.c`, in function `read_xcf_level()`: When reading fails, the `xcf_level *` varible `l` gets freed but the function does not return and continues using the variable.
<details><summary>Warning</summary>
<p>
```c
[ 65%] Building C object CMakeFiles/SDL3_image-shared.dir/src/IMG_xcf.c.o
/path/to/SDL_image/src/IMG_xcf.c:584:54: warning: Use of memory after it is freed [clang-analyzer-unix.Malloc]
584 |         l->tile_file_offsets = (Uint64 *)SDL_realloc(l->tile_file_offsets, sizeof(*l->tile_file_offsets) * (i+1));
|                                                      ^
/path/to/SDL_image/src/IMG_xcf.c:903:9: note: Assuming 'src' is non-null
903 |     if (!src) {
|         ^~~~
/path/to/SDL_image/src/IMG_xcf.c:903:5: note: Taking false branch
903 |     if (!src) {
|     ^ …
```
> src/IMG_xcf.c:read_xcf_level(): return NULL when read fails

- examples/showanim.c
In the example `showanim.c` individual textures are destroyed but the memory block `textures` is not freed.
<details><summary>Warning</summary>
<p>
```c
[ 82%] Building C object CMakeFiles/showanim.dir/examples/showanim.c.o
/path/to/SDL_image/examples/showanim.c:224:5: warning: Potential leak of memory pointed to by 'textures' [clang-analyzer-unix.Malloc]
224 |     SDL_DestroyRenderer(renderer);
|     ^
/path/to/SDL_image/examples/showanim.c:89:10: note: Assuming the condition is false
89 |     if ( ! argv[1] ) {
|          ^~~~~~~~~
/path/to/SDL_image/examples/showanim.c:89:5: note: Taking false branch
89 |     if ( ! argv[1] ) {
|     ^
/path/to/SDL_image/examples/showanim.c:95:5: note: Loop condition is true.  Entering loop body
95 |     for ( i=1; argv[i]; ++i ) {
|     ^ …
```
> showanim.c: Fix memory leak

- src/IMG_stb.c
fixes https://github.com/libsdl-org/sdl2-compat/issues/492
While I was investigating that issue I realised that this must actually be fixed on the `SDL_image` end and not `sdl2-compat` end as I initially assumed.
This PR makes the stbimage backend path more like the libpng backend:
- If a colorkey is set along with a palette, the colorkey entry shouldn't have redundant pixel alpha of 0 as that messes up the `SDL_MapRGB` logic.
- The stbimage backend always gives 256 entries in the palette, even if less entries are required. It seems like stb image does not expose this information in its API. I have put a bit of a hacky solution to this issue. It's certainly not very efficient but is the easiest approach I could think of.
> Improve palette handling in STB backend

- src/IMG_libpng.c
This matches the default behaviour for true colour surfaces, and ensures that the transparency is displayed correctly in `showimage`.
> Enable blending by default for PNGs with alpha palettes

- src/IMG.c
See also libsdl-org/SDL#13868.
> Consistently use SDL_PIXELFORMAT_RGBA32 with Emscripten
